const textToShow = [
    "Welcome to my part of the internet, stranger. There are secrets here.",
    "Find them, and you shall find a hidden treasure.",
    "...",
    "...",
    "",
    "λ > finger `whoami`",
    "",
    "Login: coldsauce Name: Aleksić Stefan.",
    "Directory: ~coldsauce Shell: /usr/bin/zsh",
    "Mail forwarded to: stefan@stefanaleksic.com",
    "Project: Working hard to make a more open internet.",
    "About:",
    "       Software engineer that stumbled into security blue team work and fell in love with it.",
    "       Love getting my hands dirty with data. Jupyter notebooks <3",
    "       Love big data. Sometimes, I dream about my CROSS JOIN UNNESTs...",
    "       Huge art history geek with a love for Gothic Revival architecture, and medieval",
    "       craft. Talk Ruskin to me.",
    "Goal:",
    "       I have several high level goals in life.",
    "           1.) Be happy.",
    "           2.) Be kind.",
    "           3.) Make cool stuff.",
    "           4.) Stay fun.",
    "",
    "Jumble of thoughts rolled into one blog: ",
    "LINK       https://blog.stefanaleksic.com",
    "My Github has some of my favorite projects:",
    "LINK       https://github.com/coldsauce",
    "",
    "To reach out, either email me or Tweet at me (@stayfun_)",
]


export default textToShow
