const textToShow = [
  "Welcome to my part of the internet, stranger. There are secrets here.",
  "Find them, and you shall find a hidden treasure.",
  "...",
  "...",
  "",
  "λ > finger `whoami`",
  "",
  "Login: coldsauce Name: Aleksic Stefan.",
  "Directory: ~coldsauce Shell: /usr/bin/zsh",
  "Mail forwarded to: stefan@stefanaleksic.com",
  "Project: Working hard to make a more open internet.",
  "",
  "About:",
  "       Startup founder, cybersecurity expert, and art history geek.",
  "       On a quest to understand the world better. ",
  "       Side-quests include: creating AI generated art every Sunday,",
  "       reverse engineering Chromium for fun, and discovering hot sauce.",
  "",
  "Current question I am thinking a lot about: ",
  "       How can knowledge workers practice their scales?",
  "",
  "Goal:",
  "       I have several high level goals in life.",
  "           1.) Be happy.",
  "           2.) Be kind.",
  "           3.) Make cool stuff.",
  "           4.) Stay fun.",
  "",
  "Currently CEO at Plasmo, making browser extension developer tooling:",
  "LINK       https://plasmo.com",
  "Jumble of thoughts rolled into one blog: ",
  "LINK       https://blog.stefanaleksic.com",
  "My Github has some of my favorite projects:",
  "LINK       https://github.com/coldsauce",
  "",
  "To reach out, either email me or Tweet at me (@stayfun_)",
];

export default textToShow;
